name: creative8
favicon: null
layout_spectrum: 0.50454
typography_spectrum: 0.13832
title: Hermano Talastas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8b7940'
    - '#d5d0bb'
    - '#da2523'
    - '#eba30f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
